#!/usr/bin/env bash
#
# Refreshes /etc/nginx/cloudflare-ips.conf from Cloudflare's published IP
# ranges (https://www.cloudflare.com/ips-v4, .../ips-v6), tests the nginx
# config, and reloads nginx only if the test passes. Safe to run unattended
# on a schedule — it never touches nginx.conf itself, only the generated
# include file, and it backs that file up before overwriting it.
#
# Cloudflare rotates these ranges rarely, but a stale list either starts
# rejecting real Cloudflare traffic's CF-Connecting-IP (falls back to
# treating Cloudflare's edge as the client — see nginx.conf's comment on
# why that's the exact bug this whole setup fixes) or, if a range shrinks,
# leaves a no-longer-Cloudflare-owned block still trusted. Neither is
# catastrophic on its own (the app-layer LOGIN budget and DB lockout don't
# depend on this), but both defeat the point of trusting CF-Connecting-IP at
# all, so keep this current.
#
# USAGE (manual):
#   sudo ./scripts/vps/refresh-cloudflare-ips.sh
#   sudo ./scripts/vps/refresh-cloudflare-ips.sh --dry-run   # fetch + diff only, no changes
#
# CRON (as root, monthly is plenty — Cloudflare's ranges don't change often):
#   sudo crontab -e
#   0 4 1 * * /var/www/motoxplus/scripts/vps/refresh-cloudflare-ips.sh >> /var/log/nginx/cloudflare-ips-refresh.log 2>&1
#
# Also re-run manually after `git pull` if the repo's checked-in
# cloudflare-ips.conf changed, so the deployed file matches what's reviewed
# in version control instead of drifting from an unattended cron run.
set -euo pipefail

CONF_PATH="${CONF_PATH:-/etc/nginx/cloudflare-ips.conf}"
DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

log() { echo "[refresh-cloudflare-ips] $*"; }
die() { echo "[refresh-cloudflare-ips] ERROR: $*" >&2; exit 1; }

command -v curl &>/dev/null || die "curl is required"

TMP=$(mktemp)
trap 'rm -f "$TMP"' EXIT

IPV4=$(curl -sS --max-time 10 https://www.cloudflare.com/ips-v4) || die "failed to fetch ips-v4"
IPV6=$(curl -sS --max-time 10 https://www.cloudflare.com/ips-v6) || die "failed to fetch ips-v6"
[[ -n "$IPV4" ]] || die "ips-v4 response was empty — refusing to write an empty trust list"
[[ -n "$IPV6" ]] || die "ips-v6 response was empty — refusing to write an empty trust list"

{
  echo "# ============================================================================="
  echo "# CLOUDFLARE IP RANGES — trusted for the CF-Connecting-IP header"
  echo "# ============================================================================="
  echo "# Generated by scripts/vps/refresh-cloudflare-ips.sh from"
  echo "# https://www.cloudflare.com/ips-v4 and https://www.cloudflare.com/ips-v6 —"
  echo "# do not hand-edit; re-run the script instead (it overwrites this file)."
  echo "#"
  echo "# Last refreshed: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
  while IFS= read -r range; do
    [[ -n "$range" ]] && echo "set_real_ip_from $range;"
  done <<< "$IPV4"
  while IFS= read -r range; do
    [[ -n "$range" ]] && echo "set_real_ip_from $range;"
  done <<< "$IPV6"
  echo "real_ip_header CF-Connecting-IP;"
} > "$TMP"

if [[ -f "$CONF_PATH" ]]; then
  if diff -q "$CONF_PATH" "$TMP" &>/dev/null; then
    log "No change — $CONF_PATH already matches Cloudflare's current ranges."
    exit 0
  fi
  log "Diff against current $CONF_PATH:"
  diff -u "$CONF_PATH" "$TMP" || true
else
  log "No existing $CONF_PATH — this will create it."
fi

if $DRY_RUN; then
  log "Dry run — not writing $CONF_PATH or reloading nginx."
  exit 0
fi

[[ $EUID -ne 0 ]] && die "must run as root to write $CONF_PATH and reload nginx (try sudo)"

if [[ -f "$CONF_PATH" ]]; then
  cp "$CONF_PATH" "${CONF_PATH}.bak"
  log "Backed up previous version to ${CONF_PATH}.bak"
fi

cp "$TMP" "$CONF_PATH"
log "Wrote $CONF_PATH"

if nginx -t 2>&1; then
  nginx -s reload
  log "nginx config valid, reloaded."
else
  log "nginx -t FAILED — restoring previous version and NOT reloading."
  [[ -f "${CONF_PATH}.bak" ]] && cp "${CONF_PATH}.bak" "$CONF_PATH"
  die "refused to reload with an invalid config; restored the previous $CONF_PATH"
fi
